#!/usr/bin/env ruby
# frozen_string_literal: true

require "irb"
require "cyclotone"

TOPLEVEL_BINDING.receiver.extend(Cyclotone::DSL)
stream = Cyclotone::Stream.instance

at_exit do
  stream.stop
  stream.scheduler.backend.close if stream.scheduler.backend.respond_to?(:close)
end

Signal.trap("INT") do
  stream.hush
  stream.scheduler.backend.panic if stream.scheduler.backend.respond_to?(:panic)
  exit(130)
end

puts "Cyclotone REPL"
puts "DSL loaded: d1..d16, s, gain, setcps, hush"

IRB.start
